version: '3.8'
services:
  wos-svg:
    build: .
    container_name: wos-svg
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "/root/database.sqlite:/app/database/database.sqlite"
      - "/root/.env:/app/.env"
    tty: true
    stdin_open: true
    restart: unless-stopped
